name: Run Telegram Bot

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'  # প্রতি ঘন্টায় রান করবে
  workflow_dispatch:  # ম্যানুয়ালি রান করার অপশন

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Python 3.x ভার্সন ব্যবহার করবে

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt  # requirements.txt থেকে প্রয়োজনীয় মডিউল ইনস্টল করবে

      - name: Run the bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: python zx.py
