name: Run Telegram Bot

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'  # প্রতি ঘন্টায় রান করবে
  workflow_dispatch:  # ম্যানুয়ালি রান করার অপশন

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run the bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: python zx.py
